services:
  db:
    image: postgres:15
    container_name: vmsm_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres_vmsm:/var/lib/postgresql/data
      - ./db_backup:/backup
    ports:
      - "5433:5432"



  redis:
    image: redis:alpine
    container_name: vmsm_redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./redis_vmsm:/data
    ports:
      - "6380:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379/0
    ports:
      - "4000:4000"
    volumes:
      - ./static_vmsm:/vmsh/static

