# Generated by Django 5.1.6 on 2025-02-17 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manageaccount',
            old_name='home_server',
            new_name='client_user',
        ),
    ]
