# Generated by Django 5.1.6 on 2025-02-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_server', '0003_alter_clientuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageaccount',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
