# Generated by Django 5.1.6 on 2025-02-20 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_server', '0005_alter_manageaccount_pass_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLimitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('increase_limit', 'Increase  Limit'), ('decrease_limit', 'Decrease Limit'), ('other', 'Other')], max_length=100)),
                ('new_limit ', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
