# Generated by Django 5.1.6 on 2025-02-20 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_server', '0006_userlimithistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlimithistory',
            old_name='new_limit ',
            new_name='new_limit',
        ),
    ]
