# Generated by Django 5.1.6 on 2025-02-20 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_server', '0007_rename_point_userlimithistory_new_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientuser',
            old_name='limits',
            new_name='limits',
        ),
    ]
