# Generated by Django 5.1.6 on 2025-02-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_server', '0008_rename_balance_clientuser_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageaccount',
            name='otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
