# Generated by Django 5.1.6 on 2025-04-14 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_server', '0009_manageaccount_otp'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='manageaccount',
            table='ManageAccount',
        ),
        migrations.AlterModelTable(
            name='requestlog',
            table='RequestLog',
        ),
    ]
